### ISSUE TITLE
Close conection

### ISSUE THREAD

**Issue by alisonjr** [Bajdzis/vscode-awesome-tree#12]
how can i close a connection? Which command can I use?

**Comment by Bajdzis** [comment]
Extension "Awesome tree" not create any connection. This extension observes file system events and attempts to automate your work (artificial intelligence). https://marketplace.visualstudio.com/items?itemName=bajdzis.awesome-tree


Maybe you mean my second extension https://github.com/Bajdzis/vscode-database for SQL server ?  Unfortunately, it does not yet support the closing conection. https://github.com/Bajdzis/vscode-database/issues/152
